name: CI

on:
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    name: Определение где произошло изменение
    runs-on: ubuntu-latest
    outputs:
      code: ${{ steps.filter.outputs.code }}
      docs: ${{ steps.filter.outputs.docs }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            code:
              - 'code/**'
            docs:
              - 'docs/**'

  lint_and_test:
    name: Линтеры и тесты
    needs: changes
    if: ${{ needs.changes.outputs.code == 'true' }}
    uses: ./.github/workflows/lint_test.yml

  deploy_dev:
    name: Разворачивание тестового бота
    runs-on: ubuntu-latest
    needs: lint_and_test
    environment:
      name: dev
      url: ${{ vars.BOT_URL }}
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3

      - name: Копирование репозитория на дев-сервер
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          source: "**/*,!docs/**/*,!.github/**/*,Makefile"
          target: "secretary"
          rm: true

      - name: Разворачивание тестового бота
        uses: appleboy/ssh-action@v1.2.1
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          ADMIN_TG_ID: ${{ secrets.ADMIN_TG_ID }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          envs: BOT_TOKEN, ADMIN_TG_ID
          script: cd ~/secretary/code && docker compose up -d --build && docker system prune -f

  qa_approve:
    name: Апрув от QA
    runs-on: ubuntu-latest
    needs: deploy_dev
    environment: QA
    steps:
      - name: Апрув получен!
        run: exit 0

  team_approve:
    name: Апрув от команды
    runs-on: ubuntu-latest
    environment: Team
    needs: [changes]
    if: ${{ needs.changes.outputs.docs == 'true' }}
    steps:
      - name: Апрув получен!
        run: exit 0

  lead_approve:
    name: Апрув от тимлида
    runs-on: ubuntu-latest
    needs: [qa_approve, team_approve]
    if: ${{ !cancelled() && !failure() }}
    environment: Lead
    steps:
      - name: Апрув получен!
        run: exit 0
