name: Изменения в коде

on:
  pull_request:
    branches: [master]
    paths: ["code/**"]
  workflow_dispatch:

jobs:
  lint_and_test:
    name: Проверка линтерами и прогон тестов
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3

      - name: Установка Python3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install -r code/requirements.txt -r code/requirements_dev.txt

      - name: Проверка линтерами
        run: ruff check code

      - name: Прогон тестов
        run: exit 0

  deploy_dev:
    name: Разворачивание тестового бота
    runs-on: ubuntu-latest
    needs: lint_and_test
    steps:
      - name: Разворачивание тестового бота
        run: exit 0

  qa_approve:
    name: Апрув от QA
    runs-on: ubuntu-latest
    needs: deploy_dev
    environment: QA
    steps:
      - name: Апрув получен!
        run: exit 0

  lead_approve:
    name: Апрув от тимлида
    runs-on: ubuntu-latest
    needs: qa_approve
    environment: Lead
    steps:
      - name: Апрув получен!
        run: exit 0
