name: Изменения в коде

on:
  pull_request:
    branches: [master]
    paths: ["code/**"]
  workflow_dispatch:

jobs:
  lint_and_test:
    name: Проверка линтерами и прогон тестов
    runs-on: ubuntu-latest
    steps:
      - name: Проверка линтерами
        run: exit 0

      - name: Прогон тестов
        run: exit 0

  deploy_dev:
    name: Разворачивание тестового бота
    runs-on: ubuntu-latest
    needs: lint_and_test
    steps:
      - name: Разворачивание тестового бота
        run: exit 0

  qa_approve:
    name: Апрув от QA
    runs-on: ubuntu-latest
    needs: deploy_dev
    environment: QA
    steps:
      - name: Апрув получен!
        run: exit 0

  lead_approve:
    name: Апрув от тимлида
    runs-on: ubuntu-latest
    needs: qa_approve
    environment: Lead
    steps:
      - name: Апрув получен!
        run: exit 0
