name: Изменения в коде

on:
  pull_request:
    branches: [master]
    paths: ["code/**"]
  workflow_dispatch:

jobs:
  lint_and_test:
    name: Проверка линтерами и прогон тестов
    runs-on: ubuntu-latest
    steps:
      - name: Проверка линтерами
        run: echo Ошибок не обнаружено!

      - name: Прогон тестов
        run: echo Тесты прошли успешно!

  deploy_dev:
    name: Разворачивание тестового бота
    runs-on: ubuntu-latest
    needs: lint_and_test
    steps:
      - name: Вывод строки в консоль
        run: |
          echo Hello from ${{ github.job }}

  qa_approve:
    name: Апрув от QA
    runs-on: ubuntu-latest
    needs: deploy_dev
    environment: QA
    steps:
      - run: echo Апрув получен!

  lead_approve:
    name: Апрув от тимлида
    runs-on: ubuntu-latest
    needs: qa_approve
    environment: Lead
    steps:
      - run: echo Апрув получен!
