name: Изменения в документации

on:
  pull_request:
    branches: [master]
    paths: ["docs/**"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  team_approve:
    name: Апрув от команды
    runs-on: ubuntu-latest
    environment: Team
    steps:
      - name: Апрув получен!
        run: exit 0
