name: Изменения в корне репозитория

on:
  pull_request:
    branches: [master]
    paths-ignore: ["code/**", "docs/**"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lead_approve:
    name: Апрув от тимлида
    runs-on: ubuntu-latest
    environment: Lead
    steps:
      - name: Апрув получен!
        run: exit 0
